### ISSUE TITLE
Title should be in center

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#103]
Title should be in center

**URL tested:** https://www.marsdenmarketing.com/data-driven-marketing

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fdata-driven-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/data-driven-marketing) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/f616d831b87632bfe262590a7872eda2587cd878/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/f616d831b87632bfe262590a7872eda2587cd878/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fdata-driven-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/data-driven-marketing) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48697952-b925f980-ec07-11e8-8e8d-38f9344f79f9.png)
fixed
