### ISSUE TITLE
Should these be left aligned?

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#105]
we need to confirm that it should be left aligned with client.

**URL tested:** https://www.marsdenmarketing.com/b2b-marketing-strategy

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fb2b-marketing-strategy&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/b2b-marketing-strategy) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S9 Plus |
| Browser | Mobile_chrome |
| Operating System | Android 8.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 6.2 in - 6.2 x 2.9 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/cb07e1261954bbd5c225cf780906c6ffc67929e1/realdroid_Samsung_Galaxy_S9_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/cb07e1261954bbd5c225cf780906c6ffc67929e1/realdroid_Samsung_Galaxy_S9_Plus.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fb2b-marketing-strategy&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/b2b-marketing-strategy) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48698440-e58e4580-ec08-11e8-870b-9de24121b0b3.png)
fixed
