### ISSUE TITLE
wrong position

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#107]
This should be in center( This mean for all logos in this section)

**URL tested:** https://www.marsdenmarketing.com/powering-leads

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-leads&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-leads) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/1cdbeec1ad1f3b46d83dece2736576b9536f3cc0/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/1cdbeec1ad1f3b46d83dece2736576b9536f3cc0/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-leads&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-leads) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48698725-a3193880-ec09-11e8-8bd6-a55272aa2f4f.png)
fixed
