### ISSUE TITLE
Little padding

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#109]
can we add little padding for logos on left and right side

**URL tested:** https://www.marsdenmarketing.com/powering-leads

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-leads&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-leads) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/6066df35d18786ccf75117b478d237eebb9445ef/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/6066df35d18786ccf75117b478d237eebb9445ef/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-leads&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-leads) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
fixed
![image](https://user-images.githubusercontent.com/4739198/48699090-7dd8fa00-ec0a-11e8-9b92-c2faf86f063d.png)
