### ISSUE TITLE
We need to grow section

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#11]
White space which we need to remove

**URL tested:** https://www.marsdenmarketing.com/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/17e01a6592f473600f94c9d9af0c2a870e3b4549/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/17e01a6592f473600f94c9d9af0c2a870e3b4549/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
fixed
![image](https://user-images.githubusercontent.com/4739198/48554636-c178ee80-e900-11e8-9311-8a2d372130d6.png)

**Comment by rashedaleecom** [comment]
Fixed.
