### ISSUE TITLE
img is cut

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#111]
this Img is cut

**URL tested:** https://www.marsdenmarketing.com/inbound-marketing-agency

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Finbound-marketing-agency&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/inbound-marketing-agency) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/8539fb4d0a39c1f1a3475c17b453af8642faaff2/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/8539fb4d0a39c1f1a3475c17b453af8642faaff2/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Finbound-marketing-agency&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/inbound-marketing-agency) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48699586-9e558400-ec0b-11e8-8596-bb414eb56d0a.png)
fixed
