### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#113]
We need to add here little padding

**URL tested:** https://www.marsdenmarketing.com/sales-marketing-alignment

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fsales-marketing-alignment&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/sales-marketing-alignment) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/886459e423be810264dab6a01e65e682d2135c7c/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/886459e423be810264dab6a01e65e682d2135c7c/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fsales-marketing-alignment&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/sales-marketing-alignment) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48699961-8af6e880-ec0c-11e8-9063-d0f046b8b73f.png)
fixed padding
