### ISSUE TITLE
Top padding for title

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#114]
We need to add little top padding for title

**URL tested:** https://www.marsdenmarketing.com/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1600x1200&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1600x1200 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/dfc677d97b80d660fa12e0da24ad6bcee3e3e228/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/dfc677d97b80d660fa12e0da24ad6bcee3e3e228/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1600x1200&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48700198-3c961980-ec0d-11e8-9a0e-141e69705b90.png)
fixed
