### ISSUE TITLE
Gif in vertical center

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#115]
Can we put this gif in vertical center

**URL tested:** https://www.marsdenmarketing.com/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1600x1200&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1600x1200 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/9d4551f58b785db1e5c42246346e1cebeef405db/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/9d4551f58b785db1e5c42246346e1cebeef405db/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1600x1200&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
hype animation resizing automaticly
