### ISSUE TITLE
Center

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#117]
Can we put this content in vertical center

**URL tested:** https://www.marsdenmarketing.com/b2b-public-relations-services

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1600x1200&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fb2b-public-relations-services&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/b2b-public-relations-services) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1600x1200 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/597c96b9d7700e21c4d58511fbceac859c93059f/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/597c96b9d7700e21c4d58511fbceac859c93059f/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1600x1200&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fb2b-public-relations-services&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/b2b-public-relations-services) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
managing divis based on content alignment controlled with script
