### ISSUE TITLE
displaced

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#118]
It should be vertically and horizontally aligned. 

**URL tested:** https://www.marsdenmarketing.com/powering-growth

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPad+Pro&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-growth&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-growth) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPad Pro |
| Browser | Tablet_safari |
| Operating System | iOS 11.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 9.7 in - 5.8 x 7.8 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/205c849d62167bd94011de5c8d60038785823a0a/realios_iPad_Pro.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/205c849d62167bd94011de5c8d60038785823a0a/realios_iPad_Pro.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPad+Pro&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-growth&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-growth) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48701332-07d79180-ec10-11e8-93d7-22aae36001fc.png)
fixed
