### ISSUE TITLE
wrong position

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#119]
Mobile is on wrong position

**URL tested:** https://www.marsdenmarketing.com/sales-marketing-alignment

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1600x1200&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fsales-marketing-alignment&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/sales-marketing-alignment) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1600x1200 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/f457256a7fc8a290cde55259c7fee8928342e8e1/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/f457256a7fc8a290cde55259c7fee8928342e8e1/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1600x1200&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fsales-marketing-alignment&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/sales-marketing-alignment) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
client used image managing height auto as client instruct us to not manage image height
