### ISSUE TITLE
Client section

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#12]
Text is too close to the top and bottom

**URL tested:** https://www.marsdenmarketing.com/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/cc8d9de2aea2b3ec5fae5dc60116923e6c906c46/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/cc8d9de2aea2b3ec5fae5dc60116923e6c906c46/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48552376-3f85c700-e8fa-11e8-98fa-844e2bf8f063.png)
fixed
