### ISSUE TITLE
Displaced

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#120]
should v and h aligned.

**URL tested:** https://www.marsdenmarketing.com/b2b-marketing-strategy

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPad+Pro&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fb2b-marketing-strategy&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/b2b-marketing-strategy) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPad Pro |
| Browser | Tablet_safari |
| Operating System | iOS 11.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 9.7 in - 5.8 x 7.8 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/76c41274f9bb011974a73c69200557651cfa8ce0/realios_iPad_Pro.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/76c41274f9bb011974a73c69200557651cfa8ce0/realios_iPad_Pro.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPad+Pro&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fb2b-marketing-strategy&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/b2b-marketing-strategy) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48702738-79fda580-ec13-11e8-9e9e-f80be1720192.png)
fixed
