### ISSUE TITLE
Padding isn't the same

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#121]
Padding isn't the same

**URL tested:** https://www.marsdenmarketing.com/technology-optimization

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1600x1200&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Ftechnology-optimization&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/technology-optimization) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1600x1200 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/890ebd56f106382868971b74a6a838730241e793/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/890ebd56f106382868971b74a6a838730241e793/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1600x1200&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Ftechnology-optimization&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/technology-optimization) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48702846-d06ae400-ec13-11e8-9612-e19a698e29aa.png)
fixed
