### ISSUE TITLE
Alignment and spacing issues

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#123]
starting point for 1 is not same, also remove bottom padding and make it standard.

**URL tested:** https://www.marsdenmarketing.com/powering-leads

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPad+Pro&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-leads&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-leads) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPad Pro |
| Browser | Tablet_safari |
| Operating System | iOS 11.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 9.7 in - 5.8 x 7.8 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/240f1a9f2dcdd1d97ecacfb0473ba5be500f57ae/realios_iPad_Pro.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/240f1a9f2dcdd1d97ecacfb0473ba5be500f57ae/realios_iPad_Pro.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPad+Pro&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-leads&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-leads) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48707642-e8e1fb00-ec21-11e8-99c4-ceb7bc681191.png)
fixed
