### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#126]
Can we reduce little text here because it is cut on bottom

**URL tested:** https://www.marsdenmarketing.com/powering-growth

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-growth&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-growth) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/d46b22fb40a20ab98a145ddae49b95e0640beb46/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/d46b22fb40a20ab98a145ddae49b95e0640beb46/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-growth&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-growth) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
fixed
