### ISSUE TITLE
Logo is to big

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#127]
Logo is to big

**URL tested:** https://www.marsdenmarketing.com/account-based-marketing

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Faccount-based-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/account-based-marketing) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/511d2cc05fa381ec71654fc8eb3240d342382f4e/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/511d2cc05fa381ec71654fc8eb3240d342382f4e/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Faccount-based-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/account-based-marketing) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
fixed
