### ISSUE TITLE
Logo section

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#128]
This logo section is wrong. Logos are to small

**URL tested:** https://www.marsdenmarketing.com/digital-advertising

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fdigital-advertising&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/digital-advertising) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/cb11ca1a2a4c7902ea649180cabea096a88f76be/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/cb11ca1a2a4c7902ea649180cabea096a88f76be/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fdigital-advertising&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/digital-advertising) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48702287-5c7c0c00-ec12-11e8-9116-760ff8355e0b.png)
fixed
