### ISSUE TITLE
Can we have text in line 2

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#131]
Can we have text in line 

**URL tested:** https://www.marsdenmarketing.com/technology-optimization

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Ftechnology-optimization&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/technology-optimization) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/de38d5a44182a9b173a47a153f24d6324dd40acf/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/de38d5a44182a9b173a47a153f24d6324dd40acf/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Ftechnology-optimization&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/technology-optimization) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
images based icon added by client with this we can not stop line breaking of text
