### ISSUE TITLE
We need to grow section

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#14]
we have too big white space

**URL tested:** https://www.marsdenmarketing.com/

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/1616611b4a5de461b51d1848bd66d0d915d46415/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/1616611b4a5de461b51d1848bd66d0d915d46415/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48552990-1a925380-e8fc-11e8-9923-ae3fc3cd3d55.png)
fixed this issue kindly check
