### ISSUE TITLE
Clients section

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#15]
Too close to the top and bottom

**URL tested:** https://www.marsdenmarketing.com/

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/2a7b6f0b5c7759ddf8e5a2a8bac0a454fa858768/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/2a7b6f0b5c7759ddf8e5a2a8bac0a454fa858768/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48553058-4e6d7900-e8fc-11e8-8143-9e9a4fa7b144.png)
fixed this issue kindly review

**Comment by rashedaleecom** [comment]
this issue has been fixed.
