### ISSUE TITLE
Our Guiding Pri...

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#24]
Can we fix this section somehow?

**URL tested:** https://www.marsdenmarketing.com/why-marsden-marketing

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fwhy-marsden-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/why-marsden-marketing) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S9 Plus |
| Browser | Mobile_chrome |
| Operating System | Android 8.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 6.2 in - 6.2 x 2.9 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/1b7dbc998caa53feead7ca3242c9c61fce7b49fb/realdroid_Samsung_Galaxy_S9_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/1b7dbc998caa53feead7ca3242c9c61fce7b49fb/realdroid_Samsung_Galaxy_S9_Plus.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fwhy-marsden-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/why-marsden-marketing) to reproduce the issue on Browserstack:**

**Comment by rashedaleecom** [comment]
Fixed.

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48627688-03746400-e9d7-11e8-992d-6421a89e95c3.png)
we cant not control hype animation based on script
