### ISSUE TITLE
Vertical HR

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#29]
This line should be in vertical center

**URL tested:** https://www.marsdenmarketing.com/b2b-branding-services

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fb2b-branding-services&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/b2b-branding-services) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S9 Plus |
| Browser | Mobile_chrome |
| Operating System | Android 8.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 6.2 in - 6.2 x 2.9 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/912d2af912ac3716cf956402c05d0c960d4683c3/realdroid_Samsung_Galaxy_S9_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/912d2af912ac3716cf956402c05d0c960d4683c3/realdroid_Samsung_Galaxy_S9_Plus.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fb2b-branding-services&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/b2b-branding-services) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
fixed 
![image](https://user-images.githubusercontent.com/4739198/48565015-5daeef80-e919-11e8-890b-526e890aca36.png)
