### ISSUE TITLE
white space

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#39]
we need to decrease white space

**URL tested:** https://www.marsdenmarketing.com/technology-optimization

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Ftechnology-optimization&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/technology-optimization) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S9 Plus |
| Browser | Mobile_chrome |
| Operating System | Android 8.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 6.2 in - 6.2 x 2.9 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/7d7bdb3f1e604f4e8338c19edafa7fa6e3879184/realdroid_Samsung_Galaxy_S9_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/7d7bdb3f1e604f4e8338c19edafa7fa6e3879184/realdroid_Samsung_Galaxy_S9_Plus.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Ftechnology-optimization&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/technology-optimization) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
Spaces added by client

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48641180-c3bf7380-e9fa-11e8-8fda-f0da87ecfc8d.png)
