### ISSUE TITLE
Some of ...

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#42]
We need to add left and right padding and we need to put logos in vertical center because in this moment we have some logos over slider bullet points

**URL tested:** https://www.marsdenmarketing.com/technology-optimization

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Ftechnology-optimization&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/technology-optimization) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S9 Plus |
| Browser | Mobile_chrome |
| Operating System | Android 8.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 6.2 in - 6.2 x 2.9 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/3bec118f8b5e311293a41ea6b0797a9729a6a0ee/realdroid_Samsung_Galaxy_S9_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/3bec118f8b5e311293a41ea6b0797a9729a6a0ee/realdroid_Samsung_Galaxy_S9_Plus.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Ftechnology-optimization&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/technology-optimization) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48640966-1f3d3180-e9fa-11e8-923a-4b48cefda867.png)
spaces added by client

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48641119-8f4bb780-e9fa-11e8-8391-870e865ce7a4.png)
fixed
