### ISSUE TITLE
How MArsde....

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#47]
can we add right padding?

**URL tested:** https://www.marsdenmarketing.com/data-driven-marketing

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fdata-driven-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/data-driven-marketing) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S9 Plus |
| Browser | Mobile_chrome |
| Operating System | Android 8.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 6.2 in - 6.2 x 2.9 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/617f071e5c3ac4248efff7851d6bd89c7c22cb14/realdroid_Samsung_Galaxy_S9_Plus.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/617f071e5c3ac4248efff7851d6bd89c7c22cb14/realdroid_Samsung_Galaxy_S9_Plus.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fdata-driven-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/data-driven-marketing) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
fixed
![image](https://user-images.githubusercontent.com/4739198/48634696-fa3fc300-e9e7-11e8-98b2-b47bb01581f8.png)
