### ISSUE TITLE
SubtItile

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#5]
bottom of subtitle is cut

**URL tested:** https://www.marsdenmarketing.com/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=2048x1536&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 2048x1536 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/d076d81634d62379f0c452a198bf6c200feb33eb/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/d076d81634d62379f0c452a198bf6c200feb33eb/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=2048x1536&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48550968-eae04d00-e8f5-11e8-8948-d76db9627fb9.png)
here is my side view kindly review coming fine at my side
