### ISSUE TITLE
Bottom padding

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#50]
Can we add little bottom padding?

**URL tested:** https://www.marsdenmarketing.com/careers/

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fcareers%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/careers/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1600x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/730f16739d40fa3ad52ef3434a9a6f31824a609b/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/730f16739d40fa3ad52ef3434a9a6f31824a609b/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fcareers%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/careers/) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
> Can we add little bottom padding?
Bottom padding added you can check,









> 
> **URL tested:** https://www.marsdenmarketing.com/careers/
> 
> Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fcareers%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/careers/) on Browserstack
> 
> Property	Value
> Browser	Safari 11.1
> Operating System	OS X High Sierra
> Resolution	1600x768
> **Screenshot Attached**
> [Screenshot URL](https://live.browserstack.com/issue-tracker/730f16739d40fa3ad52ef3434a9a6f31824a609b/machs_safari_11.1.jpg)![Screenshot URL](https://camo.githubusercontent.com/cd166965bd78cd9c645124bf19e6fb8e5e6de6b7/68747470733a2f2f6c6976652e62726f77736572737461636b2e636f6d2f69737375652d747261636b65722f373330663136373339643430666133616435326566333433346139613666333138323461363039622f6d616368735f7361666172695f31312e312e6a7067)
> 
> **Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fcareers%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/careers/) to reproduce the issue on Browserstack:**

**Comment by rashedaleecom** [comment]
Fixed.
