### ISSUE TITLE
Blog 1

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#58]
Is this part by design?

**URL tested:** https://www.marsdenmarketing.com/blog

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fblog&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/blog) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1600x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/9aad2fa4ed3ff48131000a33ea1ae69a8edd384d/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/9aad2fa4ed3ff48131000a33ea1ae69a8edd384d/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fblog&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/blog) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
not created by us and not part of task.
