### ISSUE TITLE
Top Padding

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#59]
Can we have the same padding on top like on bottom?

**URL tested:** https://www.marsdenmarketing.com/methodology

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fmethodology&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/methodology) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1600x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/6f480f4e2c743a4f9f676fc8d2e95a9d607e4d2e/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/6f480f4e2c743a4f9f676fc8d2e95a9d607e4d2e/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fmethodology&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/methodology) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48628078-1c314980-e9d8-11e8-9c38-d6ec4f79e740.png)
fixed
