### ISSUE TITLE
Resources 1

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#60]
Is this by design? Because on other page this title is on left side aligned

**URL tested:** https://www.marsdenmarketing.com/marketing-resources/

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fmarketing-resources%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/marketing-resources/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1600x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/d0ee766bf0b9840c31941044ba140e3d6c38eac7/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/d0ee766bf0b9840c31941044ba140e3d6c38eac7/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fmarketing-resources%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/marketing-resources/) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48628145-45ea7080-e9d8-11e8-9687-caf733015573.png)
added by client
