### ISSUE TITLE
We're section

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#61]
Can this text be in vertical center because in this moment we have less white space above text

**URL tested:** https://www.marsdenmarketing.com/why-marsden-marketing

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fwhy-marsden-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/why-marsden-marketing) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1600x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/f6546f704eb005c636735cc62a7c5ef42c707186/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/f6546f704eb005c636735cc62a7c5ef42c707186/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fwhy-marsden-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/why-marsden-marketing) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48628439-fbb5bf00-e9d8-11e8-80df-9519041cfe89.png)
fixed
