### ISSUE TITLE
Where do you fall....

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#62]
Can we have this content on Hover in vertical center?

**URL tested:** https://www.marsdenmarketing.com/powering-growth

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-growth&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-growth) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1600x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/a12209c7dd1b3935872a5faed73a73324367dc0f/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/a12209c7dd1b3935872a5faed73a73324367dc0f/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-growth&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-growth) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
iframe based module client added can not control
