### ISSUE TITLE
Hr issues

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#63]
We need to decrease size of this line to be like the rest of line and should be in vertical center

**URL tested:** https://www.marsdenmarketing.com/content-marketing-strategy

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fcontent-marketing-strategy&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/content-marketing-strategy) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1600x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/7fc78bffed20753633655e0a56e05f1747b94896/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/7fc78bffed20753633655e0a56e05f1747b94896/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fcontent-marketing-strategy&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/content-marketing-strategy) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48636467-c4510d80-e9ec-11e8-8cde-f13d92f03bd2.png)
![image](https://user-images.githubusercontent.com/4739198/48636477-ca46ee80-e9ec-11e8-8580-6c16a46233ba.png)
fixed
