### ISSUE TITLE
gif section

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#7]
it is not in center.

**URL tested:** https://www.marsdenmarketing.com/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=2048x1536&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 2048x1536 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/8ee0f293afcd698a14ec08bf1f74ed2b97eff5ed/win10_ie_11.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/8ee0f293afcd698a14ec08bf1f74ed2b97eff5ed/win10_ie_11.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=safari&zoom_to_fit=true&full_screen=true&resolution=2048x1536&url=https%3A%2F%2Fwww.marsdenmarketing.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
coming fine on real devices its apparently coming here because it have scrollbar on bottom as the main screen is not as much big as the browser stack give.
