### ISSUE TITLE
White space

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#77]
Can we reduce little bit this white space?

**URL tested:** https://www.marsdenmarketing.com/methodology

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fmethodology&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/methodology) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 7 |
| Browser | Mobile_safari |
| Operating System | iOS 10.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/8960be7241451b09caa3a800d66adc509bae59ad/realios_iPhone_7.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/8960be7241451b09caa3a800d66adc509bae59ad/realios_iPhone_7.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fmethodology&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/methodology) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48629404-50f2d000-e9db-11e8-91e8-4e6c0a19630d.png)
