### ISSUE TITLE
Process...

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#78]
Can this part be in vertical center?In this moment we have more space on bottom then on top

**URL tested:** https://www.marsdenmarketing.com/methodology

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fmethodology&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/methodology) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 7 |
| Browser | Mobile_safari |
| Operating System | iOS 10.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/44b9596a02c3a7cc9f42fd55e51ca61805e237e8/realios_iPhone_7.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/44b9596a02c3a7cc9f42fd55e51ca61805e237e8/realios_iPhone_7.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fmethodology&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/methodology) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48629520-a29b5a80-e9db-11e8-934b-14f66304d246.png)
top and bottom space same now
