### ISSUE TITLE
White space 2

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#79]
can we reduce little this white space?

**URL tested:** https://www.marsdenmarketing.com/our-work

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Four-work&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/our-work) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 7 |
| Browser | Mobile_safari |
| Operating System | iOS 10.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/604940342afa3b80c1596be5da7fbb91ff2be54d/realios_iPhone_7.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/604940342afa3b80c1596be5da7fbb91ff2be54d/realios_iPhone_7.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Four-work&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/our-work) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48629630-f7d76c00-e9db-11e8-890f-224b2b5dbe4a.png)
fixed
