### ISSUE TITLE
wrong position for title

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#81]
wrong position for title

**URL tested:** https://www.marsdenmarketing.com/why-marsden-marketing

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fwhy-marsden-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/why-marsden-marketing) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 7 |
| Browser | Mobile_safari |
| Operating System | iOS 10.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/fa4a5b099416d4b019fc3930bbc3e9e1afb3212e/realios_iPhone_7.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/fa4a5b099416d4b019fc3930bbc3e9e1afb3212e/realios_iPhone_7.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fwhy-marsden-marketing&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/why-marsden-marketing) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48634194-d29c2b00-e9e6-11e8-92c2-991fd772e861.png)
hype animation but fixed the text using css
