### ISSUE TITLE
Constant padding

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#84]
We need to have the same padding for bottom and top for this section

**URL tested:** https://www.marsdenmarketing.com/digital-advertising

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fdigital-advertising&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/digital-advertising) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 7 |
| Browser | Mobile_safari |
| Operating System | iOS 10.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/05b614911bcad14954df22a63c187f888250203c/realios_iPhone_7.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/05b614911bcad14954df22a63c187f888250203c/realios_iPhone_7.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fdigital-advertising&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/digital-advertising) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48639672-18acbb00-e9f6-11e8-917b-1770aebc270e.png)
fixed
