### ISSUE TITLE
Hr line 

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#86]
can we have this line in vertical center?

**URL tested:** https://www.marsdenmarketing.com/b2b-public-relations-services

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fb2b-public-relations-services&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/b2b-public-relations-services) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 7 |
| Browser | Mobile_safari |
| Operating System | iOS 10.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/5a4bfc4946d3c7cca9c4f73a8d417cec1291d751/realios_iPhone_7.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/5a4bfc4946d3c7cca9c4f73a8d417cec1291d751/realios_iPhone_7.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fb2b-public-relations-services&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/b2b-public-relations-services) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48639801-878a1400-e9f6-11e8-8995-27adc38525f8.png)
fixed
