### ISSUE TITLE
top padding

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#90]
Can we add little bit top padding?

**URL tested:** https://www.marsdenmarketing.com/technology-optimization

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Ftechnology-optimization&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/technology-optimization) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 7 |
| Browser | Mobile_safari |
| Operating System | iOS 10.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/bf9bd2018baf067483425b2201fba632f5dcb6f9/realios_iPhone_7.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/bf9bd2018baf067483425b2201fba632f5dcb6f9/realios_iPhone_7.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Ftechnology-optimization&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/technology-optimization) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48636948-28c09c80-e9ee-11e8-9f7a-de61eb61b52a.png)
fixed much we can control as this is hype generated animation we can not control it with css as much
