### ISSUE TITLE
Title should be in center

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/mars#99]
Title should be in center

**URL tested:** https://www.marsdenmarketing.com/powering-growth

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-growth&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-growth) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/c3067b193e23675ca1620429df32b07b54212ee5/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/c3067b193e23675ca1620429df32b07b54212ee5/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.marsdenmarketing.com%2Fpowering-growth&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.marsdenmarketing.com/powering-growth) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48696987-4582ed00-ec05-11e8-94f1-c56a9f79520b.png)
fixed coming in center as the first word is bigger and its hype animation
